export const PRODUCTS = [
  {
    id: 'pp-packing-bags',
    name: 'PP Packing Bags',
    desc: 'High-strength 100% virgin PP bags — 51 microns — printed with your brand, ideal for industrial and retail packaging.',
    size: '3" – 22" · 51 Micron',
    apps: 'Industrial, Food, Chemical, Retail',
    img: '/images/products/pp-packing-bags.png',
    details: [
      'Made from 100% virgin polypropylene granules.',
      'Available in custom widths from 3" to 22" and lengths to suit your line.',
      'Strong heat seal performance for packing, retail and industrial applications.',
      'Bulk supply ready for warehouse and export distribution.',
    ],
  },
  {
    id: 'pp-treatment-rolls',
    name: 'PP Treatment Rolls',
    desc: 'Smooth, uniform-thickness PP treatment rolls — 51 micron, 100% food grade, 100% recyclable — engineered for automatic packing lines.',
    size: '3" – 22" · 51 Micron',
    apps: 'In plastic printing industries',
    img: '/images/products/pp-treatment-roll.png',
    details: [
      'Precision wound rolls for consistent processing on automatic machines.',
      'Food-grade finish with excellent clarity and low friction.',
      'Customizable core diameter, width and length for your equipment.',
      'Suitable for bag making, wrapping and film conversion.',
    ],
  },
  {
    id: 'ld-packing-bags',
    name: 'LD Packing Bags',
    desc: 'Flexible 100% virgin LLDPE bags with strong heat seals, excellent transparency and moisture resistance — bulk-packed in bundles.',
    size: '4" – 20"',
    apps: 'Chemical, Food, General',
    img: '/images/products/ld-packing-bags.png',
    details: [
      'Virgin LLDPE formulation for tear resistance and clarity.',
      'Available in custom thicknesses for industrial and retail uses.',
      'Designed for easy sealing and moisture protection.',
      'Ideal for chemicals, food ingredients, hardware and packaging.',
    ],
  },
  {
    id: 'pp-gerbera-cover',
    name: 'PP Gerbera Cover',
    desc: 'Crystal-clear PP sleeves precision-cut for Gerbera flowers — bundled and ready for export cold-chain use.',
    size: '4 × 3',
    apps: 'For protection for flower',
    img: '/images/flower/pp-gerbera-cover.png',
    details: [
      'High-clarity sleeves to protect blooms during transit.',
      'Sized for Gerbera stems with a neat finish and easy loading.',
      'Perforated options available for breathability.',
      'Perfect for export-ready flower bunches.',
    ],
  },
  {
    id: 'pp-gypsophila-orchid-sleeves',
    name: 'PP Gypsophila / Orchid Sleeves',
    desc: 'Long crystal-clear PP flower sleeves with breather perforations — protect bloom quality during transportation and storage.',
    size: '20 × 25',
    apps: 'Gypsophila, Orchid Export',
    img: '/images/flower/pp-gypso-orchid-sleeves.png',
    details: [
      'Long-length sleeves for delicate export flowers.',
      'Breather perforations maintain freshness and prevent moisture build-up.',
      'Excellent optical clarity for premium presentation.',
      'Designed for cold-chain transport and retail display.',
    ],
  },
  {
    id: 'pp-chrysanthemum-sleeves',
    name: 'PP Chrysanthemum (Shevanti) Sleeves',
    desc: 'Ventilated PP sleeves engineered specifically for Chrysanthemum / Shevanti with premium clarity and long-lasting protection.',
    size: '18 × 25',
    apps: 'Chrysanthemum, Shevanti Export',
    img: '/images/flower/pp-chrysanthemum-sleeves.png',
    details: [
      'Ventilated sleeve design for air circulation and bloom health.',
      'Strong and durable for export handling and storage.',
      'Clear film keeps product visibility high for retail buyers.',
      'Custom printing available for branding and product identification.',
    ],
  },
];
